package fpt.entity;
// Generated Oct 15, 2016 12:30:21 AM by Hibernate Tools 4.3.1



/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private String code;
     private String name;
     private Double price;
     
    public Products() {
    }

	
    public Products(String code, String name) {
        this.code = code;
        this.name = name;
    }
    public Products(String code, String name, Double price) {
       this.code = code;
       this.name = name;
       this.price = price;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


